{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "universal-python.fullname" . }}
  labels:
    {{- include "universal-python.labels" . | nindent 4 }}
  annotations:
    {{- include "universal-python.deploymentAnnotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "universal-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "universal-python.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "universal-python.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "universal-python.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "universal-python.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $key, $val := .Values.application.ports }}
            - name: {{ $key }}
              containerPort: {{ $val }}
              protocol: TCP
            {{- end }}
          env:
            {{- range $key, $val := .Values.application.env }}
            - name: {{ $key }}
              {{- if $val | toString | regexMatch "^\".*" }}
              value: {{ $val }}
              {{- else }}
              value: {{ $val | quote }}
              {{- end }}
            {{- end }}
            {{- if .Values.externalSecret.enabled }}
            {{- range $secretKey, $secretVal := .Values.externalSecret.secretData }}
            - name: {{ $secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "universal-python.fullname" . }}-external-secret
                  key: {{ $secretVal.property }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.probes.startup.port }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configMap.enabled }}
          volumeMounts:
            - name: {{ .Values.configMap.volumeName | default "config-volume" }}
              mountPath: {{ .Values.configMap.mountPath | default "/app/config" }}       
      volumes:
        - name: {{ .Values.configMap.volumeName | default "config-volume" }}
          configMap:
            name: {{ .Values.configMap.name | default "configMap" }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
