{{- if .Values.logging.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{ include "universal-python.fullname" . }}-flow
  namespace:  {{ .Values.logging.namespace | default "default" }}
spec:
  filters:
    - parser:
        {{- range $key, $val := .Values.logging.flow.parser }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
        parse:
          type: multi_format
          patterns:
            {{- range .Values.logging.flow.patterns }}
            - format: {{ . | quote }}
            {{- end }}
        {{- if .Values.logging.flow.buffer.enabled }}
    - record_modifier:
        records:
          - application_name: {{ .Values.logging.flow.application_name | quote }}
          {{- end }}
  localOutputRefs:
    - logging-output-{{ .Values.logging.flow.application_name | quote }}
  match:
    - select:
        labels:
          app: {{  .Values.logging.flow.application_name | quote }}
{{- end }}
