{{- if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name}}-{{ .Values.application.instance }}-migration-upgrade"
  labels:
    {{- include "universal-python.labels" . | nindent 4 }}
  annotations:
    {{- include "universal-python.prehook-5" . | nindent 4 }} 
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "universal-python.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.migrations.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.nameMigration }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: {{ .Values.migrations.command }}
          imagePullPolicy: {{ .Values.migrations.pullPolicy }}
          env:
            {{- range $key, $val := .Values.application.env }}
            - name: {{ $key }}
              {{- if $val | toString | regexMatch "^\".*" }}
              value: {{ $val }}
              {{- else }}
              value: {{ $val | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.migrations.resourceLimits.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
