{{- if .Values.monitoring.podmonitor.enabled -}}
{{- $fullName := include "universal-python.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "universal-python.fullname" . }}
  labels:
    {{- include "universal-python.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      {{- include "universal-python.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - interval: {{ .Values.monitoring.podmonitor.interval }}
      path: {{ .Values.monitoring.podmonitor.path }}
      port: {{ .Values.monitoring.podmonitor.port }}
      scrapeTimeout: {{ .Values.monitoring.podmonitor.scrapeTimeout }}
{{- end }}
